/***********************************************************************************************************************************************
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: *
*                                                   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                                     *
* By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.           *
************************************************************************************************************************************************/
public class SecondQ {
    public static void main(String[] args) {
        System.out.println(new SecondQ().run());
    }
    public String run() {
        int sum = 0;
        int x = 1;  // current Fib
        int y = 2;  // next Fib
        while (x <= 4000000) {
            if (x % 2 == 0)
                sum += x;
            int z = x + y;
            x = y;
            y = z;
        }
        return Integer.toString(sum);
    }
}

